# Generated by Django 3.1.1 on 2020-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, unique=True)),
                ('nick', models.CharField(default='', max_length=20, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
